title: Tahanima Chowdhury
description: Software Engineer, QA @ Therap (BD) Ltd.
baseurl: "/tahanima.github.io/remple/"
url: ""

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
