title: Nazia Shehnaz Joynab
description: CS undergraduate at Military Institute of Science and Technology
baseurl: "/CV/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "ncoder76@gmail.com"
linkedin: "https://www.linkedin.com/in/naziashehnaz/"
github: "https://github.com/Geek-a-Byte"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
